version: "3"

services:
  daysign:
    image: daysign98tang:latest
    container_name: daysign98tang
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./cookies:/app/cookies
      - ./.env:/app/.env
    environment:
      - TZ=Asia/Shanghai